### PR TITLE
Fix: Modified handler -> handler.Filename when checking if file is up…

### PR DESCRIPTION
**Pull request by kentaro-a**
Hello taigacute.
Thanks for your nice application! I'm new to Golang and learning with your app!!
BTW I found some issues and fixed them like this.
Could you check or review them?

Fix: Modified handler -> handler.Filename when checking if file is uploaded or not in TaskAdd.
Fix: Mkdir /files/ if it doesn't exist in TaskAdd.

### CODE REVIEW

**Comment by glepnir** [comment]
merged thanks

**Comment by glepnir** [comment]
by the way this is a simple web applictaition. it has some issues like this  and   better error handler 。

**Comment by kentaro-a** [comment]
thank you for merging.
this app and your code help me to learn English very efficiently!

**Comment by glepnir** [comment]
really？my pleasure

**Pull request merged**
